name: Mirror and run GitLab CI

on:
  push:
    branches:
      - 'ch[0-9]'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Mirror + trigger CI
      uses: tkf2019/gitlab-mirror-and-ci-action@master
      with:
        args: "https://git.tsinghua.edu.cn/os-lab/2024s/public/ucore-tutorial-code"
      env:
        GITLAB_HOSTNAME: "git.tsinghua.edu.cn"
        GITLAB_PROJECT_ID: "29092"
        GITLAB_PROJECT_NAME: "ucore-tutorial-code"
        GITLAB_PROJECT_TOKEN: ${{secrets.GITLAB_PROJECT_TOKEN}}
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
